# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: Dotnet Restore

- task: DotNetCoreInstaller@0
  displayName: Dotnet Install
  inputs:
    version: '2.1.300'

- task: DotNetCoreCLI@2
  displayName: Dotnet Build
  inputs:
    command: build

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Publish'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
